# fly.toml app configuration file generated for happy-word-factory-dark-sunset-4704 on 2024-12-22T13:49:58+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'happy-word-factory-dark-sunset-4704'
primary_region = 'nrt'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256'
  cpu_kind = 'shared'
  cpus = 1
